pipeline {
    agent none
    parameters {
        string(name: 'BUILD_VERSION', defaultValue: '', description: 'Build version for the distribution packages')
    }
    stages {
        stage('Preparation') {
            agent {
                kubernetes {
                    inheritFrom 'default'
                    yaml """
                    apiVersion: v1
                    kind: Pod
                    spec:
                      containers:
                      - name: alpine-preparation
                        image: alpine:latest
                        command:
                        - cat
                        tty: true
                    """
                }
            }
            steps {
                container('alpine-preparation') {
                    sh """
                    apk add --no-cache wget unzip zip composer nodejs npm tar php83 php83-curl php83-iconv php83-mbstring php83-openssl php83-phar php83-zip php83-tokenizer php83-session php83-xml php83-dom php83-xmlreader php83-xmlwriter php83-fileinfo
                    ln -s /etc/php83/php.ini /etc/php83/conf.d/php.ini
                    ln -s /etc/php83/php.d/* /etc/php83/conf.d/
                    wget https://github.com/Gamerboy59/rpxy-webui/archive/refs/heads/main.zip
                    unzip main.zip
                    mv rpxy-webui-main rpxy-webui
                    mv rpxy-webui/.env.example rpxy-webui/.env
                    cd rpxy-webui
                    composer install && npm install && npm run build
                    rm -R node_modules/
                    cd ..
                    tar -czf rpxy-webui.tar.gz rpxy-webui
                    zip -r rpxy-webui.zip rpxy-webui
                    """
                }
                archiveArtifacts artifacts: 'rpxy-webui.tar.gz, rpxy-webui.zip', allowEmptyArchive: false, fingerprint: true
                stash includes: 'rpxy-webui.tar.gz', name: 'rpxy-webui-tar'
            }
        }
        stage('Build RPM') {
            agent {
                kubernetes {
                    inheritFrom 'default'
                    yaml """
                    apiVersion: v1
                    kind: Pod
                    spec:
                      containers:
                      - name: rpm-builder
                        image: rockylinux:9
                        command:
                        - cat
                        tty: true
                    """
                }
            }
            steps {
                unstash 'rpxy-webui-tar'
                container('rpm-builder') {
                    // Prepare build environment
                    sh """
                    dnf install -y rpmdevtools tar
                    mkdir -p rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
                    mkdir -p rpxy-webui-${params.BUILD_VERSION}
                    tar -xzf rpxy-webui.tar.gz -C rpxy-webui-${params.BUILD_VERSION}/
                    mv rpxy-webui-${params.BUILD_VERSION}/rpxy-webui/.build/RPM/rpxy-webui.spec rpmbuild/SPECS/rpxy-webui.spec
                    rm -rf rpxy-webui-${params.BUILD_VERSION}/rpxy-webui/.build/
                    mv rpxy-webui-${params.BUILD_VERSION}/rpxy-webui/ rpxy-webui-${params.BUILD_VERSION}/data/
                    """

                    // Replace @BUILD_VERSION@ in control file with actual version
                    sh "sed -i 's/@BUILD_VERSION@/${params.BUILD_VERSION}/' rpmbuild/SPECS/rpxy-webui.spec"

                    // Replace @Source0@ in control file with actual version
                    sh "sed -i 's/@Source0@/rpxy-webui-${params.BUILD_VERSION}.tar.gz/' rpmbuild/SPECS/rpxy-webui.spec"

                    // Add apache2 conf
                    sh """
                    mkdir -p rpxy-webui-${params.BUILD_VERSION}/conf/
                    cat > rpxy-webui-${params.BUILD_VERSION}/conf/apache.conf <<EOF
Alias /rpxy-webui /var/www/rpxy-webui/public/

<Directory /var/www/rpxy-webui/public/>
    Options SymLinksIfOwnerMatch
    DirectoryIndex index.php
    AllowOverride All
    Require all granted

    # PHP 8+
#    <IfModule mod_php.c>
#        php_admin_value upload_tmp_dir /var/lib/rpxy-webui/tmp/
#    </IfModule>
</Directory>
EOF
                    """

                    // Build the RPM package
                    sh """
                    tar -czf rpmbuild/SOURCES/rpxy-webui-${params.BUILD_VERSION}.tar.gz rpxy-webui-${params.BUILD_VERSION}/
                    rpmbuild --define '_topdir ${WORKSPACE}/rpmbuild' --define '_version ${params.BUILD_VERSION}' -bb rpmbuild/SPECS/rpxy-webui.spec

                    # Move RPM to root for archiving
                    mv rpmbuild/RPMS/noarch/rpxy-webui-${params.BUILD_VERSION}-1.el9.noarch.rpm .
                    """
                }
                archiveArtifacts artifacts: "rpxy-webui-${params.BUILD_VERSION}-1.el9.noarch.rpm", allowEmptyArchive: false, fingerprint: true
            }
        }
        stage('Build DEB') {
            agent {
                kubernetes {
                    inheritFrom 'default'
                    yaml """
                    apiVersion: v1
                    kind: Pod
                    spec:
                      containers:
                      - name: deb-builder
                        image: debian:stable-slim
                        command:
                        - cat
                        tty: true
                    """
                }
            }
            steps {
                unstash 'rpxy-webui-tar'
                container('deb-builder') {
                    // Prepare build environment
                    sh """
                    apt-get update && apt-get install --no-install-recommends -y dpkg-dev tar
                    mkdir -p rpxy-webui_${params.BUILD_VERSION}-1_all/var/www/
                    tar -xzf rpxy-webui.tar.gz -C rpxy-webui_${params.BUILD_VERSION}-1_all/var/www/
                    mkdir -p rpxy-webui_${params.BUILD_VERSION}-1_all/DEBIAN
                    mv rpxy-webui_${params.BUILD_VERSION}-1_all/var/www/rpxy-webui/.build/DEB/control rpxy-webui_${params.BUILD_VERSION}-1_all/DEBIAN/control
                    mv rpxy-webui_${params.BUILD_VERSION}-1_all/var/www/rpxy-webui/.build/DEB/postinst rpxy-webui_${params.BUILD_VERSION}-1_all/DEBIAN/postinst
                    chmod 0755 rpxy-webui_${params.BUILD_VERSION}-1_all/DEBIAN/postinst
                    rm -R rpxy-webui_${params.BUILD_VERSION}-1_all/var/www/rpxy-webui/.build/
                    """

                    // Replace @BUILD_VERSION@ in control file with actual version
                    sh "sed -i 's/@BUILD_VERSION@/${params.BUILD_VERSION}/' rpxy-webui_${params.BUILD_VERSION}-1_all/DEBIAN/control"

                    // Add apache2 config
                    sh """
                    mkdir -p rpxy-webui_${params.BUILD_VERSION}-1_all/etc/apache2/conf-available/
                    cat > rpxy-webui_${params.BUILD_VERSION}-1_all/etc/apache2/conf-available/rpxy-webui.conf <<EOF
Alias /rpxy-webui /var/www/rpxy-webui/public/

<Directory /var/www/rpxy-webui/public/>
    Options SymLinksIfOwnerMatch
    DirectoryIndex index.php
    AllowOverride All
    Require all granted

    # PHP 8+
#    <IfModule mod_php.c>
#        php_admin_value upload_tmp_dir /var/lib/rpxy-webui/tmp/
#    </IfModule>
</Directory>
EOF
                    """

                    // Link doc files
                    sh """
                    mkdir -p rpxy-webui_${params.BUILD_VERSION}-1_all/usr/share/doc/rpxy-webui
                    ln -s rpxy-webui_${params.BUILD_VERSION}-1_all/var/www/rpxy-webui/README.md rpxy-webui_${params.BUILD_VERSION}-1_all/usr/share/doc/rpxy-webui/README
                    ln -s rpxy-webui_${params.BUILD_VERSION}-1_all/var/www/rpxy-webui/LICENSE rpxy-webui_${params.BUILD_VERSION}-1_all/usr/share/doc/rpxy-webui/COPYRIGHT
                    """

                    // Build the DEB package
                    sh "dpkg-deb --build --root-owner-group rpxy-webui_${params.BUILD_VERSION}-1_all"
                }
                archiveArtifacts artifacts: "rpxy-webui_${params.BUILD_VERSION}-1_all.deb", allowEmptyArchive: false, fingerprint: true
            }
        }
    }
}
